set -g mode-keys vi
set -g mouse on

set -g status off

set -g prefix C-a
unbind C-b
bind C-a send-prefix

setw -g mode-keys vi
bind -T copy-mode-vi 'v' send -X begin-selection
#bind -T copy-mode-vi 'V' send =X begin-selection -X select-line
bind -T copy-mode-vi 'y' send -X copy-selection-and-cancel

bind '\' split-window -h
bind - split-window -v
unbind '"'
unbind %

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind c new-window
bind n next-window
bind N previous-window

