font_file_text=Iosevka Nerd Font
position=top-right

gamemode

fps
frametime

gpu_stats
gpu_temp
gpu_core_clock

cpu_stats
cpu_temp
cpu_mhz

ram
vram

background_alpha=0.8
background_color=11111b
text_color=cdd6f4

gpu_color=eba0ac
cpu_color=cba6f7
vram_color=b4befe
ram_color=b4befe
